### ISSUE TITLE
Additional Package Dependencies on (maybe only) 18.04

### ISSUE THREAD

**Issue by knifehandz** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#6]
Hi Patrick,

I'm back again with some more issues I've discovered after upgrading to 18.04. I've upgraded since day one to 18.04, the script installed Notes perfectly. Except because I needed to type Mandarin (Taiwan traditional Chinese) and it has not worked since the upgrade. Was trying to figure out why my iBus IM wouldn't work today and to my surprise, there were also some other not-so-serious package dependencies. Just reporting back here so you are aware of these package dependencies.

ibus-gtk:i386 - for _any_ iBus input method to work in Notes (this is the most serious one for me)
libcanberra-gtk-module:i386 - event sounds
libatk-adaptor:i386, libgail-common:i386 - assistive technology bridge
gnome-themes-extra:i386 - for anyone using Adwaita or other themes (I'm using a dark theme)

I have a question to consult you as well:
If using a dark theme, everything will look somewhat coherent only when the "Operating System Theme for Low Vision" is chosen in Windows and Themes in Preferences, otherwise sometimes the text boxes (eg. To / CC / BCC in email composing) have black background and black text or white text on white background for email information fields. It's not your script's problem, but for your expertise in Notes on Linux, maybe you know something behind this theming mess.

**Comment by CTXz** [comment]
Hey Yen-Yen,

Thanks for the issue, I'll look into it!

It may come as a surprise that I rarely use Notes. This repository is simply nothing more but a child of an internship project, where I was tasked to check whether I can get IBM notes running on the companies Linux machines. I honestly didn't expect this repository to grow popular. Hence I'm always very thankful that users in need of this script are willing to contribute!

I can only assume the mess that you're describing is caused by generic GTK GUI elements conflicting with IBM notes specific GTK GUI elements. Perhaps disabling the GTK theme for the application only may lead to success: 

- [GTK - Enable/set dark theme on a per-application basis](https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis)

- [Except some applications (like VLC) from using the current gtk3 theme](https://unix.stackexchange.com/questions/407302/except-some-applications-like-vlc-from-using-the-current-gtk3-theme)

**Comment by CTXz** [comment]
The dependencies have been added with commit 21ca947664efe74c5db548fd8e17e052c2fcab79!
